name: memorare
description: 5 seconds of emotion
licence: MPL-2.0

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.3.0+7

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  cloud_firestore: 0.13.6
  cloud_functions: 0.5.0
  cross_local_storage: 1.1.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: 0.1.3
  data_connection_checker: 0.3.4
  dynamic_theme: 1.0.1
  firebase_auth: 0.16.1
  firebase_core: 0.4.5
  firebase_analytics: 5.0.11
  firebase_messaging: 6.0.16
  flushbar: 1.10.0
  flutter:
    sdk: flutter
  flutter_inner_drawer: 0.5.7+2
  flutter_mobx: 1.0.1
  flutter_sticky_header: 0.4.2
  google_fonts: 1.1.0
  mobx: 1.0.2
  mobx_codegen: 1.0.2
  share: 0.6.3+5
  simple_animations: 1.3.9
  sticky_headers: 0.1.8+1
  supercharged: 1.6.0
  url_launcher: 5.4.10

dev_dependencies:
  build_runner:
  flutter_launcher_icons: 0.7.5
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: "launcher_icon"
  image_path_android: "assets/images/app-launch-icon-android.png"
  image_path_ios: "assets/images/app-launch-icon-ios.jpg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/images/amazon.png
    - assets/images/app-icon-32.png
    - assets/images/app-icon-512.png
    - assets/images/app-icon-64.png
    - assets/images/app-icon-text.png
    - assets/images/boy-dark.png
    - assets/images/boy-light.png
    - assets/images/delete-user-dark.png
    - assets/images/delete-user-light.png
    - assets/images/employee-dark.png
    - assets/images/employee-light.png
    - assets/images/facebook.png
    - assets/images/lady-light.png
    - assets/images/lady-dark.png
    - assets/images/layers-dark.png
    - assets/images/layers-light.png
    - assets/images/lock-dark.png
    - assets/images/lock-light.png
    - assets/images/jeje-profile.jpg
    - assets/images/netflix.png
    - assets/images/page-not-found-4.png
    - assets/images/prime-video.png
    - assets/images/profile-dark.png
    - assets/images/profile-light.png
    - assets/images/textbook-dark.png
    - assets/images/textbook-light.png
    - assets/images/twitch.png
    - assets/images/twitter.png
    - assets/images/user-dark.png
    - assets/images/user-light.png
    - assets/images/world-globe.png
    - assets/images/write-email-dark.png
    - assets/images/write-email-light.png
    - assets/images/wikipedia-dark.png
    - assets/images/wikipedia-light.png
    - assets/images/youtube.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: IconsMore
      fonts:
        - asset: assets/fonts/IconsMore.ttf
